// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBva-Ok-JclbjoU41Vscfyl-k9HVdZ-fXg',
    appId: '1:409623045746:web:6d5087b12b55de2ef644eb',
    messagingSenderId: '409623045746',
    projectId: 'flutter-chat-app-17ea3',
    authDomain: 'flutter-chat-app-17ea3.firebaseapp.com',
    databaseURL: 'https://flutter-chat-app-17ea3-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-17ea3.appspot.com',
    measurementId: 'G-P0XPRCBH3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA37-4XAP6SHSCJsrSMvxxJua_VNkdWJVk',
    appId: '1:409623045746:android:1103675fab639e59f644eb',
    messagingSenderId: '409623045746',
    projectId: 'flutter-chat-app-17ea3',
    databaseURL: 'https://flutter-chat-app-17ea3-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-17ea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7uMFv0XgeXNWPE3qlLf9g34GLmc0eO30',
    appId: '1:409623045746:ios:1b7f33b7327b2744f644eb',
    messagingSenderId: '409623045746',
    projectId: 'flutter-chat-app-17ea3',
    databaseURL: 'https://flutter-chat-app-17ea3-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-17ea3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7uMFv0XgeXNWPE3qlLf9g34GLmc0eO30',
    appId: '1:409623045746:ios:734758c15efb870df644eb',
    messagingSenderId: '409623045746',
    projectId: 'flutter-chat-app-17ea3',
    databaseURL: 'https://flutter-chat-app-17ea3-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-17ea3.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
